### ISSUE TITLE
scrollbar-y taking up space

### ISSUE THREAD

**Issue by sarumie** [sarumie/todo-list#7]
![msedge_igJ2Ng5Hj8](https://user-images.githubusercontent.com/86160898/165685390-e298cd0f-c549-484f-812c-5a21d655a095.gif)
taking up space the content when scrollbar is displayed

**Comment by sarumie** [comment]
Fixed it with css
```css
html {
  overflow-y: overlay;
}
```
